# this is the configuration file for the test suite.
# be very careful to modify it.

---
test_name: JIRA-Function-Test
test_desc: A demo function test for JIRA
test_cases_path: test-cases/firefox/
test_input_path: test-input/
test_output_path: test-output/firefox/

base_url: https://ralphwen.atlassian.net
implicit_wait: 30 # implicit wait time in seconds
time_out: 120 # time out time in seconds. default in selenium is 60, changing to 120 here.

username: ralph.wen@gmail.com
password: 12345678